$('.owll-carousel').carousel({
    
    loop:true,
    rtl:true,
    nav:true,
  margin:10,
  responsiveClass:true,
  responsive:{
      0:{
          items:14,
          nav:false
      },
      600:{
          items:,
          nav:false
      },
      1000:{
          items:4,
          nav:true,
          loop:true
      }
  }
})
